apiVersion: v1
kind: Service
metadata:
  name: {{ include "mp.fullname" . }}
  labels:
    {{- include "mp.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: alb
spec:
  # type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app : {{ include "mp.fullname" . }}